# docker-compose.yml

version: '3.8'

services:
  web:
    build: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn src.main:app --host 0.0.0.0'
    volumes:
      - .:/app
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=postgresql://roland:postgres@db:5432/postgres
      - JWT_SECRET=505300e590c07dcec010a31b8de8000642ef4bb08948b3d0045a12e1fbc3a76b
      - JWT_ALG=HS256
    depends_on:
      - db

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
        - 5432
    environment:
      - POSTGRES_USER=roland
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

volumes:
  postgres_data: